### ISSUE TITLE
Which method do you use to generate  initial pose/shape estimations in demo?

### ISSUE THREAD

**Issue by YongtaoGE** [nicolasugrinovic/size_depth_disambiguation#2]
Thanks for your great work! Could you explain which method is used in  [coco demo](https://drive.google.com/file/d/1rwWMkVtdOcxABOL5G96EA7tv-gkECqdB/view?usp=sharing)?

**Comment by nicolasugrinovic** [comment]
Hi, thanks for your interest in our work. For the initial estimations in this demo, we use the code implementation from "Coherent Reconstruction of Multiple Humans from a Single Image" ([CRMH](https://github.com/JiangWenPL/multiperson)). 

If you want to generate more examples you have to copy the output from CRMH with the correct name format.

**Comment by YongtaoGE** [comment]
Thanks. I would have a try.

**Comment by YongtaoGE** [comment]
@nicolasugrinovic Hi, could you provide a visualization demo that renders optimized multi-person results in the image?
